CREATE TABLE USERMEMBER(
    MEM_ID VARCHAR2(20) NOT NULL,
    MEM_PW VARCHAR2(300) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    MEM_ID_CARD VARCHAR2(20) NOT NULL,
    MEM_EMAIL VARCHAR2(50) NOT NULL,
    MEM_PHONE VARCHAR2(13) NOT NULL,
    MEM_ADDRESS VARCHAR2(300),
    MEM_BALANCE NUMBER NOT NULL
);
COMMENT ON COLUMN USERMEMBER.MEM_ID IS '사용자아이디';
COMMENT ON COLUMN USERMEMBER.MEM_PW IS '사용자비밀번호';
COMMENT ON COLUMN USERMEMBER.MEM_NAME IS '사용자이름';
COMMENT ON COLUMN USERMEMBER.MEM_ID_CARD IS '주민번호';
COMMENT ON COLUMN USERMEMBER.MEM_EMAIL IS '사용자이메일';
COMMENT ON COLUMN USERMEMBER.MEM_PHONE IS '사용자휴대폰';
COMMENT ON COLUMN USERMEMBER.MEM_ADDRESS IS '사용자주소';
COMMENT ON COLUMN USERMEMBER.MEM_BALANCE IS '잔액';



CREATE TABLE BOARD(
    MEM_ID VARCHAR2(20) NOT NULL,
    BOARD_NUM VARCHAR2(20) NOT NULL,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_DATE DATE,
    GOODS_PRICE NUMBER NOT NULL,
    GOODS_IMG VARCHAR2(1000) NOT NULL,
    BOARD_CATEGORY VARCHAR2(5) NOT NULL
    
);
COMMENT ON COLUMN BOARD.MEM_ID IS '작성자 아이디';
COMMENT ON COLUMN BOARD.BOARD_NUM IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글작성일';
COMMENT ON COLUMN BOARD.GOODS_PRICE IS '상품금액';
COMMENT ON COLUMN BOARD.GOODS_IMG IS '상품이미지';
COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS '상품카테고리';

CREATE TABLE BOARD_QUESTION(
    MEM_ID VARCHAR2(20) NOT NULL,
    BOARD_NUM NUMBER NOT NULL,
    BOARD_QUESTION_NUM VARCHAR2(20) NOT NULL,
    BOARD_QUESTION_DATE DATE,
    BOARD_QUESTION_CONTENT VARCHAR2(1000) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    BOARD_QUESTION_SECRET CHAR(1) NULL 
);

COMMENT ON COLUMN BOARD_QUESTION.MEM_ID IS '회원 아이디';
COMMENT ON COLUMN BOARD_QUESTION.BOARD_NUM IS '게시글 번호';
COMMENT ON COLUMN BOARD_QUESTION.BOARD_QUESTION_NUM IS '댓글번호';
COMMENT ON COLUMN BOARD_QUESTION.BOARD_QUESTION_DATE IS '댓글작성일';
COMMENT ON COLUMN BOARD_QUESTION.BOARD_QUESTION_CONTENT IS '댓글내용';
COMMENT ON COLUMN BOARD_QUESTION.MEM_NAME IS '댓글작성자';
COMMENT ON COLUMN BOARD_QUESTION.BOARD_QUESTION_SECRET IS '댓글 공개 여부';

CREATE TABLE BOARD_REQUESTRION(
    BOARD_NUM NUMBER NOT NULL,
    BOARD_REQUESTION_NUM VARCHAR2(20) NOT NULL,
    BOARD_REQUESTION_DATE DATE,
    BOARD_REQUESTION_CONTNET VARCHAR2(1000) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    BOARD_REQUESTION_SECRET CHAR(1) NOT NULL
);

COMMENT ON COLUMN BOARD_REQUESTRION.BAORD_NUM IS '게시글 번호';
COMMENT ON COLUMN BOARD_REQUESTRION.BOARD_REQUESTION_NUM IS '댓글번호';
COMMENT ON COLUMN BOARD_REQUESTRION.BOARD_REQUESTION_DATE IS '댓글작성일';
COMMENT ON COLUMN BOARD_REQUESTRION.BOARD_REQUESTION_CONTNET IS '댓글내용';
COMMENT ON COLUMN BOARD_REQUESTRION.MEM_NAME IS '댓글작성자';
COMMENT ON COLUMN BOARD_REQUESTRION.BOARD_REQUESTION_SECRET IS '댓글 공개 여부';

CREATE TABLE ORDERLIST(
    ORDER_NUM NUMBER NOT NULL,
    BOARD_NUM VARCHAR2(20) NOT NULL 
);

COMMENT ON COLUMN MYORDER.ORDER_NUM IS '주문번호';
COMMENT ON COLUMN MYORDER.BOARD_NUM IS '게시글번호';

CREATE TABLE PAYMENT(
    PAYMENT_NUM (20) NOT NULL,
    MEM_ID VARCHAR2(20) NOT NULL,
    PAYMENT_PRICE NUMBER NOT NULL,
    PAYMENT_DATE DATE,
    PAYMENT_STATE VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN PAYMENT.PAYMENT_NUM IS '결제 번호';
COMMENT ON COLUMN PAYMENT.MEM_ID IS '결제자';
COMMENT ON COLUMN PAYMENT.PAYMENT_PRICE IS '결제 금액';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제일';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATE IS '결제 상태';

CREATE TABLE GOODSPAYMENT(
    PAYMENT_NUM NUMBER NOT NULL,
    SELL_MEM_ID VARCHAR2(20) NOT NULL,
    ORDER_MEM_ID VARCHAR2(20) NOT NULL,
    BOARD_NUM NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATE VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN GOODSPAYMENT.PAYMENT_NUM IS '결제번호';
COMMENT ON COLUMN GOODSPAYMENT.SELL_MEM_ID IS '판매자 아이디';
COMMENT ON COLUMN GOODSPAYMENT.ORDER_MEM_ID IS '구매자 아이디';
COMMENT ON COLUMN GOODSPAYMENT.BOARD_NUM IS '게시물 번호';
COMMENT ON COLUMN GOODSPAYMENT.ORDER_DATE IS '결제일';
COMMENT ON COLUMN GOODSPAYMENT.ORDER_STATE IS '결제상태';

select * from GOODSPAYMENT;
select * from payment;

SELECT G.PAYMENT_NUM paymetnNum,B.board_title boardTitle,G.SELL_MEM_ID sellMemId, G.ORDER_MEM_ID orderMemId, G.BOARD_NUM boardNum, G.ORDER_DATE orderDate,B.GOODS_PRICE goodsPrice ,G.ORDER_STATE orderState
	FROM GOODSPAYMENT G
    INNER JOIN
    BOARD B
    ON
    G.board_num = B.board_num
	WHERE SELL_MEM_ID = 'admin';

select * from board_question;
select * from board;